[package]
name = "perf_heavy_features"
version = "0.1.0"
edition = "2024"

[lib]
name = "cpu_bound_features"
create-type = ["cdylib"]

[dependencies]

[dependencies.pyo3]
version = "0.25.0"
features = ["abi3-py313", "extension-module"]


